# Generated by Django 6.0.5 on 2026-07-03 04:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayAnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='holiday',
            name='announced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='announced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holiday_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holiday',
            name='announcement_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holiday',
            name='ceo_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='event_type',
            field=models.CharField(choices=[('holiday', 'Holiday'), ('extra_working', 'Extra Working Day')], default='holiday', max_length=20),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['event_type'], name='dashboard_h_event_t_41fd80_idx'),
        ),
        migrations.AddField(
            model_name='holidayannouncementread',
            name='holiday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='dashboard.holiday'),
        ),
        migrations.AddField(
            model_name='holidayannouncementread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_reads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='holidayannouncementread',
            constraint=models.UniqueConstraint(fields=('user', 'holiday'), name='uniq_user_holiday_read'),
        ),
    ]
