# Generated by Django 6.0.5 on 2026-07-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_salary_salaryincrementrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin (HR)'), ('ceo', 'CEO'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
