# Generated by Django 6.0.5 on 2026-07-03 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_praiseletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('director', 'Director'), ('admin', 'Admin (HR)'), ('ceo', 'CEO'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
        migrations.CreateModel(
            name='CompanyHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ceo_user', models.ForeignKey(blank=True, limit_choices_to={'role': 'ceo'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hierarchy_as_ceo', to=settings.AUTH_USER_MODEL)),
                ('director_user', models.ForeignKey(blank=True, limit_choices_to={'role': 'director'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hierarchy_as_director', to=settings.AUTH_USER_MODEL)),
                ('primary_hr_user', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hierarchy_as_hr', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company hierarchy',
                'verbose_name_plural': 'Company hierarchy',
            },
        ),
    ]
