# Generated by Django 6.0.5 on 2026-07-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_employeepersonalprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='praiseletter',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='praise_letters/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='praiseletter',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
