# Generated by Django 6.0.5 on 2026-07-02 07:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('working_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Half Day', 'Half Day'), ('Absent', 'Absent'), ('Full Day', 'Full Day')], default='Absent', max_length=20)),
                ('is_late', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date'], name='attendance__date_61f2e1_idx'), models.Index(fields=['employee', 'date'], name='attendance__employe_08d913_idx'), models.Index(fields=['status'], name='attendance__status_132c06_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='uniq_employee_date_attendance')],
            },
        ),
    ]
