# Generated by Django 6.0.5 on 2026-07-03 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_overtime_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceregularizationrequest',
            name='ceo_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='attendanceregularizationrequest',
            name='ceo_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceregularizationrequest',
            name='ceo_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ceo_regularization_overrides', to=settings.AUTH_USER_MODEL),
        ),
    ]
