# Generated by Django 6.0.5 on 2026-07-03 07:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_leaverequest_payslip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Office', help_text='Label for this office location.', max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Office latitude (WGS84).', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Office longitude (WGS84).', max_digits=9, null=True)),
                ('allowed_radius_meters', models.PositiveIntegerField(default=100, help_text='Maximum allowed distance from office coordinates (meters).')),
                ('allowed_public_ips', models.TextField(blank=True, help_text='One public IP per line (or comma-separated). Used when IP verification is enabled.')),
                ('gps_verification_enabled', models.BooleanField(default=False, help_text='Require users to be within the office geofence.')),
                ('ip_verification_enabled', models.BooleanField(default=False, help_text='Require requests from configured office public IP(s).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Office Settings',
                'verbose_name_plural': 'Office Settings',
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_distance_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_user_agent',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_distance_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_user_agent',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.CreateModel(
            name='PortalAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempt', models.CharField(blank=True, max_length=64)),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('check_in', 'Check In'), ('check_out', 'Check Out')], max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'success'], name='attendance__event_t_fcc467_idx'), models.Index(fields=['created_at'], name='attendance__created_39ab0a_idx')],
            },
        ),
    ]
